"""
Django settings for AniListShare project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

WEBSITE_NAME = "AniListShare"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

DEBUG = os.getenv("DEBUG_MODE", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()
] or ["*"]

CORS_ALLOWED_ORIGINS_URLS = [
    h.strip() for h in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if h.strip()
]
CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS_URLS


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "accounts",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.mfa",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "api",
    "animeapi",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

if DEBUG:
    INSTALLED_APPS += [
        # hot reloading
        "django_browser_reload",
        "django_watchfiles",
        "silk",
    ]

    MIDDLEWARE.insert(
        1,
        # hot reloading
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    )
    MIDDLEWARE += [
        "silk.middleware.SilkyMiddleware",
    ]

ROOT_URLCONF = f"{WEBSITE_NAME}.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.website_name",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

# https://docs.djangoproject.com/en/6.0/ref/settings/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

WSGI_APPLICATION = f"{WEBSITE_NAME}.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("DATABASE_URL") and not DEBUG:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 20,  # Wait up to 20 seconds for DB lock to be released
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "EMAIL_AUTHENTICATION": True,
        "APPS": [
            {
                "client_id": os.getenv("GOOGLE_CLIENT_ID"),
                "secret": os.getenv("GOOGLE_SECRET"),
            },
        ],
        # The following provider-specific settings will be used for all apps:
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

LOGIN_URL = "/accounts/login"
LOGIN_REDIRECT_URL = "list_view"
LOGOUT_REDIRECT_URL = "/accounts/login"
ACCOUNT_SIGNUP_FIELDS = [
    "username*",
    "email*",
    "password1*",
    "password2*",
]  # it's default but i still did it

# login either using email or username
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# Determines the expiration date of email confirmation mails
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = os.getenv("EMAIL_ADDRESS")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = f"{WEBSITE_NAME} <{EMAIL_HOST_USER}>"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    # "search" is a burst rate, not a daily one: typing is the only caller, and
    # the client debounces, so a legitimate session never approaches it.
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "5000/day",
        "search": "40/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
}

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# ─── Production security settings ───────────────────────────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in (
        "true",
        "1",
        "yes",
    )
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ─── Anime metadata API (/api/v4/…, Jikan v4 compatible) ───────────────────
# Backs the `animeapi` app. Metadata is read from AniList's public GraphQL API,
# which requires no credentials; MyAnimeList (and therefore Jikan, which
# scrapes it) no longer serves live data to third parties.
ANILIST_API_URL = os.getenv("ANILIST_API_URL", "https://graphql.anilist.co")
ANILIST_USER_AGENT = os.getenv(
    "ANILIST_USER_AGENT",
    f"{WEBSITE_NAME}/1.0 (+https://github.com/sabamdarif/AniListShare)",
)
ANILIST_CONNECT_TIMEOUT = float(os.getenv("ANILIST_CONNECT_TIMEOUT", "2.5"))
ANILIST_READ_TIMEOUT = float(os.getenv("ANILIST_READ_TIMEOUT", "4"))
# Total wall-clock budget for one upstream lookup. Vercel kills long-running
# functions, so a slow AniList has to fail fast into the cache layer instead of
# hanging the request until the platform cuts it off.
ANILIST_TOTAL_TIMEOUT = float(os.getenv("ANILIST_TOTAL_TIMEOUT", "6"))
ANILIST_MAX_ATTEMPTS = int(os.getenv("ANILIST_MAX_ATTEMPTS", "2"))

# TMDb fallback for the search/detail endpoints, so web series and live-action
# films (which AniList does not carry) can be found and added to a list. With
# neither credential set the fallback is disabled and the API behaves as before.
# Supply exactly one: TMDB_API_TOKEN is a v4 Read Access Token (a long JWT, sent
# as a bearer header); TMDB_API_KEY is the short v3 key (sent as ?api_key=).
TMDB_API_URL = os.getenv("TMDB_API_URL", "https://api.themoviedb.org/3")
TMDB_API_TOKEN = os.getenv("TMDB_API_TOKEN", "")
TMDB_API_KEY = os.getenv("TMDB_API_KEY", "")
TMDB_CONNECT_TIMEOUT = float(os.getenv("TMDB_CONNECT_TIMEOUT", "2.5"))
TMDB_READ_TIMEOUT = float(os.getenv("TMDB_READ_TIMEOUT", "4"))
TMDB_TOTAL_TIMEOUT = float(os.getenv("TMDB_TOTAL_TIMEOUT", "6"))
TMDB_MAX_ATTEMPTS = int(os.getenv("TMDB_MAX_ATTEMPTS", "2"))

# (fresh_ttl, stale_ttl) in seconds, per endpoint. Entries stay cached until
# stale_ttl so a failing upstream can be served slightly old data instead of an
# error. A fresh_ttl of 0 disables caching for that endpoint.
ANIME_API_CACHE_TTLS = {
    "search": (600, 3600),
    "detail": (1800, 86400),
    "top": (1800, 21600),
    "seasonal": (3600, 86400),
    "schedules": (900, 21600),
    "genres": (86400, 604800),
    "default": (900, 21600),
}

# Shared cache, optional. With no CACHE_URL the cache is per-process — still
# useful, because Vercel reuses warm instances — while the Cache-Control headers
# on the responses are what actually share results across instances.
CACHE_URL = os.getenv("CACHE_URL", "")
if CACHE_URL:
    # Django's Redis cache backend needs redis-py, which this project does not
    # depend on by default: the shared cache that matters here is Vercel's edge,
    # not a service. Checking up front turns a would-be ImportError inside a
    # request into something that says what to do instead.
    if importlib.util.find_spec("redis") is None:
        raise ImproperlyConfigured(
            "CACHE_URL is set but the 'redis' package is not installed. "
            "Run `uv add redis`, or leave CACHE_URL unset to use the "
            "in-process cache."
        )
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CACHE_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "animeapi",
            "TIMEOUT": 604800,
            "OPTIONS": {"MAX_ENTRIES": 2000},
        }
    }
