# Generated by Django 6.0.3 on 2026-03-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_season_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='core.category'),
        ),
    ]
