# Generated by Django 6.0.2 on 2026-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animelist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="episodes_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="episodes_watched",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
